name = "SmoothedParticles"
uuid = "b7455f7a-83c6-4046-bd2b-dfe6091272a6"
version = "0.2.0"

[deps]
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
Interpolations = "a98d9a8b-a2ab-59e6-89dd-64a1c18fca59"
Match = "7eb4fadd-790c-5f42-8a69-bfa0b872bfbf"
Parameters = "d96e819e-fc66-5662-9728-84c9c7592b0a"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
QuadGK = "1fd47b50-473d-5c70-9696-f719f8f3bcdc"
ReadVTK = "dc215faf-f008-4882-a9f7-a79a826fadc3"
Roots = "f2b01f46-fcfa-551c-844a-d8ac1e96c665"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
WriteVTK = "64499a7a-5c06-52f2-abe2-ccb03c286192"

[compat]
CSV = "0.10.15"
DataFrames = "1.8.1"
Interpolations = "0.14.0"
Match = "1"
Parameters = "0.12.3"
Plots = "1.41.1"
Printf = "1.11.0"
QuadGK = "2.11.2"
ReadVTK = "0.1.3"
Roots = "2.2.10"
StaticArrays = "1"
WriteVTK = "1"
julia = "1.5"
